create table SAMPLE_TABLE (
    ID bigint generated by default as identity,
    INTEGER_CODE integer,
    STRING_CODE varchar(255),
    ORDINAL_CODE integer,
    NAME_CODE varchar(255),
    constraint SAMPLE_TABLE_PK primary key(ID)
);
